
package br.com.sigen.Interfaces;

import br.com.sigen.Modelo.Endereco;
import br.com.sigen.Modelo.Funcionario;
import br.com.sigen.dao.DAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author user
 */
public class ListarFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar_Funcionario
     */
    ListSelectionModel lsmFuncionario;
    DefaultTableModel tmFuncionario; 
    List<Funcionario> funcionarios;
    DAO<Funcionario> dao = new DAO<>(Funcionario.class);
    
    public ListarFuncionario() throws ParseException {
        super("SIGEN - Listagem de Funcionários");
        tmFuncionario = new DefaultTableModel(null, new String[]{"Nome", "Data de Cadastro", "CTPS", "CPF", "RG", "Telefone", "Celular", "Endereço"});
        initComponents();
        tFuncionario.setRowHeight(23);
        MaskFormatter maskCEP = new MaskFormatter("###.###.###-##");
        maskCEP.install(jFTCPF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRBNome = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tFuncionario = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jFTCPF = new javax.swing.JFormattedTextField();
        jBPesquisar = new javax.swing.JButton();
        jLEmpresa = new javax.swing.JLabel();
        jLVersao = new javax.swing.JLabel();

        setClosable(true);

        jRBNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRBNome.setText("Nome:");
        jRBNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listagem de Funcionários");

        jTNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNomeKeyTyped(evt);
            }
        });

        tFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tFuncionario.setModel(tmFuncionario);
        jScrollPane1.setViewportView(tFuncionario);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CPF:");

        jFTCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jBPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/pesquisar.png"))); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jLEmpresa.setText("NBNG. Todos os direitos reservados.");

        jLVersao.setText("Versão: 1.4.6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jRBNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jFTCPF)
                                .addGap(18, 18, 18)
                                .addComponent(jBPesquisar))
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLVersao))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBNome)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpresa)
                    .addComponent(jLVersao)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNomeActionPerformed

    }//GEN-LAST:event_jRBNomeActionPerformed

    private void jTNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomeKeyTyped
            jFTCPF.setText("");

            while (tmFuncionario.getRowCount() > 0) {
                tmFuncionario.removeRow(0);
            }

            
            funcionarios = new ArrayList<>();

            funcionarios = dao.buscaPorNome(jTNome.getText());
            
            for(int i = 0; i < funcionarios.size(); i++){
                System.out.println(funcionarios.get(i).getNome());
            }
            
            for(int i = 0; i < funcionarios.size(); i++){
                Endereco end = funcionarios.get(i).getEndereco();
                String e = end.getLogradouro()+" "+funcionarios.get(i).getNumero()+" "+
                        end.getBairro()+" "+end.getCidade()+" "+end.getEstado();
                
                Date data = funcionarios.get(i).getData();
                
                String d = data.toString();
                
                tmFuncionario.addRow(new String[]{funcionarios.get(i).getNome(),d,
                    funcionarios.get(i).getCtps(),
                    funcionarios.get(i).getCpf(), funcionarios.get(i).getRg(),
                    funcionarios.get(i).getTelefone(),funcionarios.get(i).getCelular(),
                    e});
            } 
    }//GEN-LAST:event_jTNomeKeyTyped

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        if (!jFTCPF.getText().equals("   .   .   -  ")) {
            jTNome.setText("");

            while (tmFuncionario.getRowCount() > 0) {
                tmFuncionario.removeRow(0);
            }

            funcionarios = new ArrayList<>();

            funcionarios = dao.buscaPorCPF(jFTCPF.getText());
            
 
            for(int i = 0; i < funcionarios.size(); i++){
                tmFuncionario.addRow(new String[]{null, null, null, null});
                tmFuncionario.setValueAt(funcionarios.get(i).getNome(), 0, 0);
                tmFuncionario.setValueAt(funcionarios.get(i).getData(), 0, 1);
                tmFuncionario.setValueAt(funcionarios.get(i).getCtps(), 0, 2);
                tmFuncionario.setValueAt(funcionarios.get(i).getCpf(), 0, 3);
                tmFuncionario.setValueAt(funcionarios.get(i).getRg(), 0, 4);
                tmFuncionario.setValueAt(funcionarios.get(i).getTelefone(), 0, 5);
                tmFuncionario.setValueAt(funcionarios.get(i).getCelular(), 0, 6);
                Endereco end = funcionarios.get(i).getEndereco();
                String e = end.getLogradouro()+" "+funcionarios.get(i).getNumero()+" "+
                        end.getBairro()+" "+end.getCidade()+" "+end.getEstado();
                tmFuncionario.setValueAt(e, 0, 7);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Favor preencher um CPF!", "ERROR 404 - Content not found!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JFormattedTextField jFTCPF;
    private javax.swing.JLabel jLEmpresa;
    private javax.swing.JLabel jLVersao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRBNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTable tFuncionario;
    // End of variables declaration//GEN-END:variables
}
