/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sigen.Interfaces;

import br.com.sigen.Modelo.Chapa;
import br.com.sigen.Modelo.Letra;
import br.com.sigen.Modelo.Quadra;
import br.com.sigen.Modelo.Venda;
import br.com.sigen.dao.DAO;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ListarTumulo extends javax.swing.JInternalFrame {

    DAO<Venda> vdao;
    DAO<Chapa> cdao;
    List<Object[]> list;
    Object[] resultado;
    Quadra quadra;
    Letra letra;
    Chapa chapa;
    Venda venda;
    DefaultTableModel tmTumulo = new DefaultTableModel(null, new String[]{"Quadra", "Letra", "Chapa", "Proprietário"}) {
        boolean[] canEdit = new boolean[]{
            false, false, false, false
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    //List de uma classe do modelo para utilização na tabela;
    ListSelectionModel lsmTumulo;
    JDesktopPane painel;

    public ListarTumulo(JDesktopPane painel) {
        super("SIGEN - Listagem de Túmulos");
        initComponents();
        tabela.setRowHeight(23);
        this.painel = painel;
        listar();
        jBRemover.setVisible(false);
        jBExcluir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLCabecalho = new javax.swing.JLabel();
        jLEmpresa = new javax.swing.JLabel();
        jLVersao = new javax.swing.JLabel();
        jBRemover = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();

        setClosable(true);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabela.setModel(tmTumulo);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabelaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLCabecalho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLCabecalho.setText("Listagem de Túmulos");

        jLEmpresa.setText("NBNG. Todos os direitos reservados.");

        jLVersao.setText("Versão: 1.4.6");

        jBRemover.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/excluir.gif"))); // NOI18N
        jBRemover.setText("Remover Venda");
        jBRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRemoverActionPerformed(evt);
            }
        });

        jBExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/excluir.gif"))); // NOI18N
        jBExcluir.setText("Excluir Chapa");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 690, Short.MAX_VALUE)
                .addComponent(jLVersao))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCabecalho)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBRemover)
                            .addComponent(jBExcluir))
                        .addGap(25, 25, 25))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBExcluir, jBRemover});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLCabecalho)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBRemover)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLVersao)
                    .addComponent(jLEmpresa)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabelaFocusGained

    }//GEN-LAST:event_tabelaFocusGained

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        jBRemover.setVisible(true);
        jBExcluir.setVisible(true);
    }//GEN-LAST:event_tabelaMouseClicked

    private void jBRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRemoverActionPerformed
        vdao = new DAO<>(Venda.class);
        Object[] resultado = list.get(tabela.getSelectedRow());
        venda = (Venda) resultado[3];
        if (venda != null) {
            vdao.remover(venda);
        }
        vdao.close();
        JOptionPane.showMessageDialog(this, "Venda"
                + " cancelada com sucesso!", "Activity Performed "
                + "Successfully", JOptionPane.INFORMATION_MESSAGE);
        limpar();
    }//GEN-LAST:event_jBRemoverActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        cdao = new DAO<>(Chapa.class);
        vdao = new DAO<>(Venda.class);
        Object[] resultado = list.get(tabela.getSelectedRow());

        chapa = (Chapa) resultado[0];
        venda = (Venda) resultado[3];
        if (venda != null) {
            vdao.remover(venda);
        }
        cdao.remover(chapa);
        cdao.close();
        vdao.close();
        JOptionPane.showMessageDialog(this, "Chapa"
                + " deletada com sucesso!", "Activity Performed "
                + "Successfully", JOptionPane.INFORMATION_MESSAGE);
        limpar();
    }//GEN-LAST:event_jBExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBRemover;
    private javax.swing.JLabel jLCabecalho;
    private javax.swing.JLabel jLEmpresa;
    private javax.swing.JLabel jLVersao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    private String montaQuery() {
        return "FROM Chapa chapa "
                + "INNER JOIN chapa.letra as letra"
                + " INNER JOIN letra.quadra as quadra"
                + " LEFT JOIN chapa.venda as venda "
                + " ORDER BY quadra.quadra,letra.letra,chapa.chapa";
    }

    private void listar() {
        vdao = new DAO<>(Venda.class);
        list = vdao.buscaAvançada(montaQuery());
        vdao.close();
        for (int i = 0; i < list.size(); i++) {
            resultado = list.get(i);
            chapa = (Chapa) resultado[0];
            letra = (Letra) resultado[1];
            quadra = (Quadra) resultado[2];
            venda = (Venda) resultado[3];

            tmTumulo.addRow(new String[]{null, null, null, null});
            tmTumulo.setValueAt(quadra.getQuadra(), i, 0);
            tmTumulo.setValueAt(letra.getLetra(), i, 1);
            tmTumulo.setValueAt(chapa.getChapa(), i, 2);
            if (venda != null) {
                tmTumulo.setValueAt(venda.getCliente().getNome(), i, 3);
            } else {
                tmTumulo.setValueAt("", i, 3);
            }
        }
    }

    private void limpar() {
        ListarTumulo cp = new ListarTumulo(painel);
        painel.add(cp);
        this.dispose();
        cp.show();
    }
}
