package br.com.sigen.Interfaces;

import br.com.sigen.Modelo.Funcionario;
import br.com.sigen.dao.DAO;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author user
 */
public class ListarFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar_Funcionario
     */
    JDesktopPane painel;
    List<Funcionario> funcionarios;
    DAO<Funcionario> dao = new DAO<>(Funcionario.class);
    String endereco;
    DefaultTableModel tmFuncionario = new DefaultTableModel(null, new String[]{"Nome", "Data de Cadastro", "Email", "CTPS", "CPF", "RG", "Telefone", "Celular", "Endereço"}) {
        boolean[] canEdit = new boolean[]{
            false, false, false, false, false, false, false, false, false
        };

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit[columnIndex];
        }
    };

    public ListarFuncionario(JDesktopPane painel) throws ParseException {
        super("SIGEN - Listagem de Funcionários");
        this.painel = painel;
        initComponents();
        tabela.setRowHeight(23);
        MaskFormatter maskCEP = new MaskFormatter("###.###.###-##");
        maskCEP.install(jFTCPF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jFTCPF = new javax.swing.JFormattedTextField();
        jBPesquisar = new javax.swing.JButton();
        jLEmpresa = new javax.swing.JLabel();
        jLVersao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Listagem de Funcionários");

        jTNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNomeKeyTyped(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabela.setModel(tmFuncionario);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CPF:");

        jFTCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jBPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/pesquisar.png"))); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jLEmpresa.setText("NBNG. Todos os direitos reservados.");

        jLVersao.setText("Versão: 1.4.6");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jFTCPF)
                                .addGap(18, 18, 18)
                                .addComponent(jBPesquisar))
                            .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLVersao))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpresa)
                    .addComponent(jLVersao)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomeKeyTyped
        jFTCPF.setText("");

        while (tmFuncionario.getRowCount() > 0) {
            tmFuncionario.removeRow(0);
        }

        funcionarios = dao.buscaPorNome(jTNome.getText());

        for (int i = 0; i < funcionarios.size(); i++) {
            endereco = funcionarios.get(i).
                    getEndereco().getLogradouro() + " " + funcionarios.get(i).
                    getNumero() + ", " + funcionarios.get(i).
                    getEndereco().getBairro() + " - " + funcionarios.get(i).
                    getEndereco().getCidade() + "/" + funcionarios.get(i).
                    getEndereco().getEstado() + " - CEP: " + funcionarios.get(i).
                    getEndereco().getCep() + "("
                    + funcionarios.get(i).getComplemento() + ")";

            tmFuncionario.addRow(new String[]{null, null, null, null});

            tmFuncionario.setValueAt(funcionarios.get(i).getNome(), i, 0);
            tmFuncionario.setValueAt(funcionarios.get(i).getData(), i, 1);
            tmFuncionario.setValueAt(funcionarios.get(i).getEmail(), i, 2);
            tmFuncionario.setValueAt(funcionarios.get(i).getCtps(), i, 3);
            tmFuncionario.setValueAt(funcionarios.get(i).getCpf(), i, 4);
            tmFuncionario.setValueAt(funcionarios.get(i).getRg(), i, 5);
            tmFuncionario.setValueAt(funcionarios.get(i).getTelefone(), i, 6);
            tmFuncionario.setValueAt(funcionarios.get(i).getCelular(), i, 7);
            tmFuncionario.setValueAt(endereco, i, 8);
        }
    }//GEN-LAST:event_jTNomeKeyTyped

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        if (!jFTCPF.getText().equals("   .   .   -  ")) {
            jTNome.setText("");

            while (tmFuncionario.getRowCount() > 0) {
                tmFuncionario.removeRow(0);
            }

            funcionarios = new ArrayList<>();

            funcionarios = dao.buscaPorCPF(jFTCPF.getText());

            for (int i = 0; i < funcionarios.size(); i++) {
                endereco = funcionarios.get(i).
                        getEndereco().getLogradouro() + " " + funcionarios.get(i).
                        getNumero() + ", " + funcionarios.get(i).
                        getEndereco().getBairro() + " - " + funcionarios.get(i).
                        getEndereco().getCidade() + "/" + funcionarios.get(i).
                        getEndereco().getEstado() + " - CEP: " + funcionarios.get(i).
                        getEndereco().getCep() + "("
                        + funcionarios.get(i).getComplemento() + ")";
                tmFuncionario.addRow(new String[]{null, null, null, null});
                tmFuncionario.setValueAt(funcionarios.get(i).getNome(), 0, 0);
                tmFuncionario.setValueAt(funcionarios.get(i).getData(), 0, 1);
                tmFuncionario.setValueAt(funcionarios.get(i).getEmail(), i, 2);
                tmFuncionario.setValueAt(funcionarios.get(i).getCtps(), 0, 3);
                tmFuncionario.setValueAt(funcionarios.get(i).getCpf(), 0, 4);
                tmFuncionario.setValueAt(funcionarios.get(i).getRg(), 0, 5);
                tmFuncionario.setValueAt(funcionarios.get(i).getTelefone(), 0, 6);
                tmFuncionario.setValueAt(funcionarios.get(i).getCelular(), 0, 7);
                tmFuncionario.setValueAt(endereco, 0, 8);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Favor preencher um CPF!", "ERROR 404 - Content not found!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (evt.getButton() != MouseEvent.BUTTON3 && evt.getClickCount() == 2) {
            try {
                AtualizaFuncionario ac
                        = new AtualizaFuncionario(funcionarios.get(tabela.getSelectedRow()), this, painel);
                ac.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(ListarCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ListarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tabelaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JFormattedTextField jFTCPF;
    private javax.swing.JLabel jLEmpresa;
    private javax.swing.JLabel jLVersao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
