/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sigen.Interfaces;

import br.com.sigen.drive.InsertGoogleDrive;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        super("SIGEN - Sistema de Gerenciamento de Necrópoles");
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/br/com/sigen/Imagens/icone.png")));
        setLocationRelativeTo(null);
        atalhos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPainel = new javax.swing.JDesktopPane();
        jMenu = new javax.swing.JMenuBar();
        jMArquivo = new javax.swing.JMenu();
        jMIBPOFF = new javax.swing.JMenuItem();
        jMIBPON = new javax.swing.JMenuItem();
        jMILogoff = new javax.swing.JMenuItem();
        jMJazigo = new javax.swing.JMenu();
        jMICadastrar_Tumulo = new javax.swing.JMenuItem();
        jMIListar_Tumulos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMICadastrar_Obito = new javax.swing.JMenuItem();
        jMIListar_Obitos = new javax.swing.JMenuItem();
        jMVendas = new javax.swing.JMenu();
        jMICadastrar_Vendas = new javax.swing.JMenuItem();
        jMIListar_Vendas = new javax.swing.JMenuItem();
        jMFuncionarios = new javax.swing.JMenu();
        jMICadastrar_Funcionarios = new javax.swing.JMenuItem();
        jMIListar_Funcionarios = new javax.swing.JMenuItem();
        jMIAlterar_Senha = new javax.swing.JMenuItem();
        jMClientes = new javax.swing.JMenu();
        jMICadastrar_Clientes = new javax.swing.JMenuItem();
        jMIListar_clientes = new javax.swing.JMenuItem();
        jMICarteirinha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/arquivo.png"))); // NOI18N
        jMArquivo.setText("Arquivo");
        jMArquivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMIBPOFF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIBPOFF.setText("Gerar Backup");
        jMIBPOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBPOFFActionPerformed(evt);
            }
        });
        jMArquivo.add(jMIBPOFF);

        jMIBPON.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIBPON.setText("Salvar Backup no Google Drive");
        jMIBPON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBPONActionPerformed(evt);
            }
        });
        jMArquivo.add(jMIBPON);

        jMILogoff.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMILogoff.setText("Logoff");
        jMILogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILogoffActionPerformed(evt);
            }
        });
        jMArquivo.add(jMILogoff);

        jMenu.add(jMArquivo);

        jMJazigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/cruz.png"))); // NOI18N
        jMJazigo.setText("Jazigos");
        jMJazigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMJazigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMJazigoActionPerformed(evt);
            }
        });

        jMICadastrar_Tumulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMICadastrar_Tumulo.setText("Cadastrar Túmulo");
        jMICadastrar_Tumulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrar_TumuloActionPerformed(evt);
            }
        });
        jMJazigo.add(jMICadastrar_Tumulo);

        jMIListar_Tumulos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIListar_Tumulos.setText("Listar Túmulos");
        jMIListar_Tumulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListar_TumulosActionPerformed(evt);
            }
        });
        jMJazigo.add(jMIListar_Tumulos);
        jMJazigo.add(jSeparator1);

        jMICadastrar_Obito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMICadastrar_Obito.setText("Cadastrar Óbito");
        jMICadastrar_Obito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrar_ObitoActionPerformed(evt);
            }
        });
        jMJazigo.add(jMICadastrar_Obito);

        jMIListar_Obitos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIListar_Obitos.setText("Listar Óbitos");
        jMIListar_Obitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListar_ObitosActionPerformed(evt);
            }
        });
        jMJazigo.add(jMIListar_Obitos);

        jMenu.add(jMJazigo);

        jMVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/agenda.png"))); // NOI18N
        jMVendas.setText("Vendas");
        jMVendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMICadastrar_Vendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMICadastrar_Vendas.setText("Cadastrar Venda");
        jMICadastrar_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrar_VendasActionPerformed(evt);
            }
        });
        jMVendas.add(jMICadastrar_Vendas);

        jMIListar_Vendas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIListar_Vendas.setText("Listar Vendas");
        jMIListar_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListar_VendasActionPerformed(evt);
            }
        });
        jMVendas.add(jMIListar_Vendas);

        jMenu.add(jMVendas);

        jMFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/funcionario.png"))); // NOI18N
        jMFuncionarios.setText("Funcionários");
        jMFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMICadastrar_Funcionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMICadastrar_Funcionarios.setText("Cadastrar Funcionários");
        jMICadastrar_Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrar_FuncionariosActionPerformed(evt);
            }
        });
        jMFuncionarios.add(jMICadastrar_Funcionarios);

        jMIListar_Funcionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIListar_Funcionarios.setText("Listar Funcionários");
        jMIListar_Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListar_FuncionariosActionPerformed(evt);
            }
        });
        jMFuncionarios.add(jMIListar_Funcionarios);

        jMIAlterar_Senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIAlterar_Senha.setText("Alterar Senha");
        jMIAlterar_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterar_SenhaActionPerformed(evt);
            }
        });
        jMFuncionarios.add(jMIAlterar_Senha);

        jMenu.add(jMFuncionarios);

        jMClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sigen/Imagens/cliente.png"))); // NOI18N
        jMClientes.setText("Clientes");
        jMClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMICadastrar_Clientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMICadastrar_Clientes.setText("Cadastrar Clientes");
        jMICadastrar_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrar_ClientesActionPerformed(evt);
            }
        });
        jMClientes.add(jMICadastrar_Clientes);

        jMIListar_clientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIListar_clientes.setText("Listar Clientes");
        jMIListar_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListar_clientesActionPerformed(evt);
            }
        });
        jMClientes.add(jMIListar_clientes);

        jMICarteirinha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMICarteirinha.setText("Imprimir Carteira de Identificação");
        jMICarteirinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICarteirinhaActionPerformed(evt);
            }
        });
        jMClientes.add(jMICarteirinha);

        jMenu.add(jMClientes);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMJazigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMJazigoActionPerformed
    }//GEN-LAST:event_jMJazigoActionPerformed

    private void jMICadastrar_TumuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrar_TumuloActionPerformed
        CadastrarTumulo ct = new CadastrarTumulo(JPainel);
        JPainel.add(ct);
        ct.show();
    }//GEN-LAST:event_jMICadastrar_TumuloActionPerformed

    private void jMIListar_TumulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListar_TumulosActionPerformed
        ListarTumulo lt = new ListarTumulo(JPainel);
        JPainel.add(lt);
        lt.show();
    }//GEN-LAST:event_jMIListar_TumulosActionPerformed

    private void jMICadastrar_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrar_ClientesActionPerformed
        try {
            CadastrarCliente cp = new CadastrarCliente(JPainel);
            JPainel.add(cp);
            cp.show();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Causa: \b" + ex,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMICadastrar_ClientesActionPerformed

    private void jMIListar_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListar_clientesActionPerformed
        try {
            ListarCliente lp = new ListarCliente(JPainel);
            JPainel.add(lp);
            lp.show();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Causa: \b" + ex,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMIListar_clientesActionPerformed

    private void jMICadastrar_FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrar_FuncionariosActionPerformed
        try {
            CadastrarFuncionario cf = new CadastrarFuncionario(JPainel);
            JPainel.add(cf);
            cf.show();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Causa: \b" + ex,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMICadastrar_FuncionariosActionPerformed

    private void jMIListar_FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListar_FuncionariosActionPerformed
        try {
            ListarFuncionario lf = new ListarFuncionario(JPainel);
            JPainel.add(lf);
            lf.show();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Causa: \b" + ex,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMIListar_FuncionariosActionPerformed

    private void jMIAlterar_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterar_SenhaActionPerformed
        AtualizaSenha as = new AtualizaSenha();
        JPainel.add(as);
        as.show();
    }//GEN-LAST:event_jMIAlterar_SenhaActionPerformed

    private void jMICadastrar_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrar_VendasActionPerformed
        CadastrarVenda cv = new CadastrarVenda();
        JPainel.add(cv);
        cv.show();
    }//GEN-LAST:event_jMICadastrar_VendasActionPerformed

    private void jMIListar_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListar_VendasActionPerformed
        ListarVenda lv = new ListarVenda();
        JPainel.add(lv);
        lv.show();
    }//GEN-LAST:event_jMIListar_VendasActionPerformed

    private void jMICadastrar_ObitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrar_ObitoActionPerformed
        try {
            CadastrarObito co = new CadastrarObito();
            JPainel.add(co);
            co.show();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Causa: \b" + ex,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMICadastrar_ObitoActionPerformed

    private void jMIListar_ObitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListar_ObitosActionPerformed
        try {
            ListarObito lo = new ListarObito();
            JPainel.add(lo);
            lo.show();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Causa: \b" + ex,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMIListar_ObitosActionPerformed

    private void jMICarteirinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICarteirinhaActionPerformed
        CarteiraCliente cc = new CarteiraCliente();
        JPainel.add(cc);
        cc.show();
    }//GEN-LAST:event_jMICarteirinhaActionPerformed

    private void jMIBPOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBPOFFActionPerformed

    }//GEN-LAST:event_jMIBPOFFActionPerformed

    private void jMIBPONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBPONActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();

            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);//use FILES_ONLY caso deseje que o usuario selecione apenas arquivos  
            fileChooser.setDialogTitle("Abrir...");

            int status = fileChooser.showOpenDialog(null);
            if (status == JFileChooser.APPROVE_OPTION) {

                File file = fileChooser.getSelectedFile();//esse é o arquivo que o usuario escolheu, faça o que quiser com ele  
                String caminho = String.valueOf(file);
                InsertGoogleDrive igd = new InsertGoogleDrive();
                igd.EnviaBackup(caminho);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Causa: \b" + ex,
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMIBPONActionPerformed

    private void jMILogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILogoffActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMILogoffActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JPainel;
    private javax.swing.JMenu jMArquivo;
    private javax.swing.JMenu jMClientes;
    private javax.swing.JMenu jMFuncionarios;
    private javax.swing.JMenuItem jMIAlterar_Senha;
    private javax.swing.JMenuItem jMIBPOFF;
    private javax.swing.JMenuItem jMIBPON;
    private javax.swing.JMenuItem jMICadastrar_Clientes;
    private javax.swing.JMenuItem jMICadastrar_Funcionarios;
    private javax.swing.JMenuItem jMICadastrar_Obito;
    private javax.swing.JMenuItem jMICadastrar_Tumulo;
    private javax.swing.JMenuItem jMICadastrar_Vendas;
    private javax.swing.JMenuItem jMICarteirinha;
    private javax.swing.JMenuItem jMIListar_Funcionarios;
    private javax.swing.JMenuItem jMIListar_Obitos;
    private javax.swing.JMenuItem jMIListar_Tumulos;
    private javax.swing.JMenuItem jMIListar_Vendas;
    private javax.swing.JMenuItem jMIListar_clientes;
    private javax.swing.JMenuItem jMILogoff;
    private javax.swing.JMenu jMJazigo;
    private javax.swing.JMenu jMVendas;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void atalhos() {
        jMClientes.setMnemonic('C');
        jMArquivo.setMnemonic('A');
        jMFuncionarios.setMnemonic('F');
        jMJazigo.setMnemonic('J');
        jMVendas.setMnemonic('V');
    }
}
